### ISSUE TITLE
Certain characters in filename cause errors

### ISSUE THREAD

**Issue by slaponicus** [shelfio/aws-lambda-libreoffice#114]
first off, I just wanted to thank you for this amazing library and the work you've put into it!

however, I did notice a small issue while using it - `canBeConvertedToPDF` returns `true` for files with certain characters (parentheses in my case) in the name, however the `convertTo` function throws the following error for the same file:

`/bin/sh: -c: line 0: syntax error near unexpected token `('`

for anyone experiencing this issue, my workaround is to `escape()` the filename before using this tool.

not a big issue, just wanted to save some hassle for anyone who runs into this : )

**Comment by vladgolubev** [comment]
Thanks for the heads up @slaponicus!

You might find https://github.com/sindresorhus/filenamify useful as well
