### ISSUE TITLE
Error while running the service in kubernetes

### ISSUE THREAD

**Issue by krisalay** [shelfio/aws-lambda-libreoffice#115]
```
{ 
  Error: ENOENT: no such file or directory, open '/opt/lo.tar.br'
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/opt/lo.tar.br' 
}
```
I am getting the above error while running the service in kubernetes/docker.
According to the documentation: `Since version 2.0.0 npm package no longer ships the 85 MB LibreOffice.` So, how do we add libreoffice in the docker container?

**Comment by vladgolubev** [comment]
Hello @krisalay 

This project is aimed to work well in AWS Lambda environment. I can't guarantee it will work in Kubernetes

If you want to try to run it in docker - you can download `lo.tar.br` from here: https://github.com/shelfio/libreoffice-lambda-layer/blob/master/layer.zip
