### ISSUE TITLE
question: how to convert s3 bucket files

### ISSUE THREAD

**Issue by jaimesangcap** [shelfio/aws-lambda-libreoffice#116]
In the example, it assumes that the file is already in the `/tmp` folder.
Is there a way to convert files inside `s3` buckets?

I'm thinking of creating a trigger for the lambda whenever there is a file uploaded in s3.
Is that possible?

**Comment by eduardoferrari** [comment]
You cannot process the file directly there, your case is the same of my, I have a trigger when a file is uploaded, than my lambda fetch the file from S3 to the /tmp, process and than, copy the result from /tmp to other folder on the S3.

**Comment by vladgolubev** [comment]
@eduardoferrari provided a great answer. It's not technically possible, S3 is not a file system but rather a REST API.

**Comment by jaimesangcap** [comment]
I appreciate your prompt response. I also found out about a demo how to do it where it downloads the S3 into the /tmp folder.

`const {writeFileSync, readFileSync} = require('fs');
const {execSync} = require('child_process');
const {parse} = require('path');
const {S3} = require('aws-sdk');

// This code runs only once per Lambda "cold start"
execSync(`curl https://s3.amazonaws.com/lambda-libreoffice-demo/lo.tar.gz -o /tmp/lo.tar.gz && cd /tmp && tar -xf /tmp/lo.tar.gz`);

const s3 = new S3({params: {Bucket: 'lambda-libreoffice-demo'}});
const convertCommand = `/tmp/instdir/program/soffice --headless --invisible --nodefault --nofirststartwizard --nolockcheck --nologo --norestore --convert-to pdf --outdir /tmp`;

exports.handler = async ({filename}) => {
  const {Body: inputFileBuffer} = await s3.getObject({Key: filename}).promise();
  writeFileSync(`/tmp/${filename}`, inputFileBuffer);

  execSync(`cd /tmp && ${convertCommand} ${filename}`);

  const outputFilename = `${parse(filename).name}.pdf`;
  const outputFileBuffer = readFileSync(`/tmp/${outputFilename}`);
https://github.com/vladgolubev/serverless-libreoffice/blob/master/STEP_BY_STEP.md
  await s3
    .upload({
      Key: outputFilename, Body: outputFileBuffer,
      ACL: 'public-read', ContentType: 'application/pdf'
    })
    .promise();

  return `https://s3.amazonaws.com/lambda-libreoffice-demo/${outputFilename}`;
};`
