### ISSUE TITLE
@shelf/aws-lambda-brotli-unpacker compiled against a different Node.js version

### ISSUE THREAD

**Issue by dawaltconley** [shelfio/aws-lambda-libreoffice#117]
Getting the following error when trying to run this in a node 10.x lambda runtime. Assume it's related to [the brotli unpacker not being updated to node 10.](https://github.com/shelfio/aws-lambda-brotli-unpacker/pull/65)

```
{
  "errorType": "Error",
  "errorMessage": "The module '/var/task/node_modules/@shelf/aws-lambda-brotli-unpacker/src/iltorb/build/bindings/iltorb.node'\nwas compiled against a different Node.js version using\nNODE_MODULE_VERSION 57. This version of Node.js requires\nNODE_MODULE_VERSION 64. Please try re-compiling or re-installing\nthe module (for instance, using `npm rebuild` or `npm install`).",
  "trace": [
    "Error: The module '/var/task/node_modules/@shelf/aws-lambda-brotli-unpacker/src/iltorb/build/bindings/iltorb.node'",
    "was compiled against a different Node.js version using",
    "NODE_MODULE_VERSION 57. This version of Node.js requires",
    "NODE_MODULE_VERSION 64. Please try re-compiling or re-installing",
    "the module (for instance, using `npm rebuild` or `npm install`).",
    "    at Object.Module._extensions..node (internal/modules/cjs/loader.js:807:18)",
    "    at Module.load (internal/modules/cjs/loader.js:653:32)",
    "    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)",
    "    at Function.Module._load (internal/modules/cjs/loader.js:585:3)",
    "    at Module.require (internal/modules/cjs/loader.js:692:17)",
    "    at require (internal/modules/cjs/helpers.js:25:18)",
    "    at Object.<anonymous> (/var/task/node_modules/@shelf/aws-lambda-brotli-unpacker/src/iltorb/index.js:8:16)",
    "    at Module._compile (internal/modules/cjs/loader.js:778:30)",
    "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)",
    "    at Module.load (internal/modules/cjs/loader.js:653:32)"
  ]
}
```

Full disclosure, haven't yet gotten a successful run on a 8.10 runtime yet so I'm not 100% sure it's that but seems likely.

If node 10.16 has native brotli support, is it possible to just lose the aws-lambda-brotli-unpacker dependency?

**Comment by harshitgupta** [comment]
Hey @vladgolubev, did you get the chance to look at the issue? Thanks

**Comment by vladgolubev** [comment]
Hey @harshitgupta, unfortunately, I haven't looked at this yet

**Comment by harshitgupta** [comment]
@vladgolubev do you have any timeline in mind? Given that the AWS team has a deadline of Jan 6, 2020, for Node 8.

**Comment by eduardoferrari** [comment]
I don't know if is useful for everybody here, but I'm working in a Python version to unpack the Brotli and than, other Python code to run it.... I haven't create yet a Git repo for it, I'm doing tests on my PC only... Just to check if is possible.... I'm using the [lambda-layer](https://github.com/shelfio/libreoffice-lambda-layer) as a base for me.

**Comment by harshitgupta** [comment]
no offense but would anybody be willing to take a bounty in order to resolve this issue in timely manner?

**Comment by dawaltconley** [comment]
It's a little out of my depth but I can give it a crack in December if nobody has gotten around to it by then. Would basically be following / debugging [this](https://github.com/vladgolubev/serverless-libreoffice/blob/master/compile.sh) on Amazon Linux 2.

**Comment by eduardoferrari** [comment]
I was able to recompile the solution on Amazon Linux 2, no errors during the compilation, the scripts ran if no problems, but I got some errors trying to run the libre office. :( My tests with python also had no success... I really don't know how to continue...

**Comment by eduardoferrari** [comment]
Ok Guys, after this update, https://github.com/shelfio/aws-lambda-brotli-unpacker/pull/83 what we need to do to solve everything? :)

**Comment by vladgolubev** [comment]
Good news: I was able to compile & run LibreOffice in the Node.js 12.x environment.
Bad news: its size is ~400 MB

The goal is to make it <250 MB when unzipped, which is what I'm working on right now

**Comment by harshitgupta** [comment]
I just want to mention one fact here that the lambda layer size counts against the lambda size(250 MB) itself so if someone could bring the size near to <250 MB, there wouldn't be much space left for the rest of the business logic and corresponding node modules. 

In that case, the solution would be to deploy a very basic lambda with only LibreOffice(this module) as a dependency and call this lambda from the rest of the lambdas.

**Comment by harshitgupta** [comment]
any update on this?

**Comment by vladgolubev** [comment]
Hey guys, yes, there are updates!

Last Friday we've published a new version which works with Node.js 10 and 12

Check out https://github.com/shelfio/aws-lambda-libreoffice/releases/tag/v3.0.0 and project README
