### ISSUE TITLE
com::sun::star::container::NoSuchElementException - On Amazon Linux 2 (Karoo) with Nodejs 10

### ISSUE THREAD

**Issue by mayurchoksi** [shelfio/aws-lambda-libreoffice#129]
I am using arn:aws:lambda:us-east-1:764866452798:layer:libreoffice-gzip:1 and trying to test the function locally (MacOS) using aws-sam-cli (SAM CLI, version 0.40.0)

I get the following error:
ERROR	Invoke Error	{"errorType":"Error","errorMessage":"Command failed: cd /tmp && /tmp/instdir/program/soffice.bin --headless --invisible --nodefault --view --nolockcheck --nologo --norestore --convert-to pdf --outdir /tmp test.txt\nterminate called after throwing an instance of 'com::sun::star::container::NoSuchElementException'\n/bin/sh: line 1:    28 Aborted                 /tmp/instdir/program/soffice.bin --headless --invisible --nodefault --view --nolockcheck --nologo --norestore --convert-to pdf --outdir /tmp test.txt\n","status":134,"signal":null,"output":[null,{"type":"Buffer","data":[]},{"type":"Buffer","data":[116,101,114,109,105,110,97,116,101,32,99,97,108,108,101,100,32,97,102,116,101,114,32,116,104,114,111,119,105,110,103,32,97,110,32,105,110,115,116,97,110,99,101,32,111,102,32,39,99,111,109,58,58,115,117,110,58,58,115,116,97,114,58,58,99,111,110,116,97,105,110,101,114,58,58,78,111,83,117,99,104,69,108,101,109,101,110,116,69,120,99,101,112,116,105,111,110,39,10,47,98,105,110,47,115,104,58,32,108,105,110,101,32,49,58,32,32,32,32,50,56,32,65,98,111,114,116,101,100,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,47,116,109,112,47,105,110,115,116,100,105,114,47,112,114,111,103,114,97,109,47,115,111,102,102,105,99,101,46,98,105,110,32,45,45,104,101,97,100,108,101,115,115,32,45,45,105,110,118,105,115,105,98,108,101,32,45,45,110,111,100,101,102,97,117,108,116,32,45,45,118,105,101,119,32,45,45,110,111,108,111,99,107,99,104,101,99,107,32,45,45,110,111,108,111,103,111,32,45,45,110,111,114,101,115,116,111,114,101,32,45,45,99,111,110,118,101,114,116,45,116,111,32,112,100,102,32,45,45,111,117,116,100,105,114,32,47,116,109,112,32,116,101,115,116,46,116,120,116,10]}],"pid":27,"stdout":{"type":"Buffer","data":[]},"stderr":{"type":"Buffer","data":[116,101,114,109,105,110,97,116,101,32,99,97,108,108,101,100,32,97,102,116,101,114,32,116,104,114,111,119,105,110,103,32,97,110,32,105,110,115,116,97,110,99,101,32,111,102,32,39,99,111,109,58,58,115,117,110,58,58,115,116,97,114,58,58,99,111,110,116,97,105,110,101,114,58,58,78,111,83,117,99,104,69,108,101,109,101,110,116,69,120,99,101,112,116,105,111,110,39,10,47,98,105,110,47,115,104,58,32,108,105,110,101,32,49,58,32,32,32,32,50,56,32,65,98,111,114,116,101,100,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,47,116,109,112,47,105,110,115,116,100,105,114,47,112,114,111,103,114,97,109,47,115,111,102,102,105,99,101,46,98,105,110,32,45,45,104,101,97,100,108,101,115,115,32,45,45,105,110,118,105,115,105,98,108,101,32,45,45,110,111,100,101,102,97,117,108,116,32,45,45,118,105,101,119,32,45,45,110,111,108,111,99,107,99,104,101,99,107,32,45,45,110,111,108,111,103,111,32,45,45,110,111,114,101,115,116,111,114,101,32,45,45,99,111,110,118,101,114,116,45,116,111,32,112,100,102,32,45,45,111,117,116,100,105,114,32,47,116,109,112,32,116,101,115,116,46,116,120,116,10]},"stack":["Error: Command failed: cd /tmp && /tmp/instdir/program/soffice.bin --headless --invisible --nodefault --view --nolockcheck --nologo --norestore --convert-to pdf --outdir /tmp test.txt","terminate called after throwing an instance of 'com::sun::star::container::NoSuchElementException'","/bin/sh: line 1:    28 Aborted                 /tmp/instdir/program/soffice.bin --headless --invisible --nodefault --view --nolockcheck --nologo --norestore --convert-to pdf --outdir /tmp test.txt","","    at checkExecSyncError (child_process.js:629:11)","    at execSync (child_process.js:666:13)","    at exports.handler.Promise.all.then (/var/task/app.js:154:13)","    at process._tickCallback (internal/process/next_tick.js:68:7)"]}

**Comment by d3netxer** [comment]
I am also getting this error when I am testing the libreoffice gzip (https://github.com/shelfio/libreoffice-lambda-layer/blob/master/layer.tar.gz.zip). I tested running the convert-to commands on my the command line in my Ubuntu 18.04 virtual machine.

I do not get this error with the layer.tar.br.zip

Running the convert-to command with the layer.tar.br.zip is hanging up often when I try to convert a pdf to a docx and it outputs many fontconfig errors and warnings in the terminal.

**Comment by vladgolubev** [comment]
We've [released a major version](https://github.com/shelfio/aws-lambda-libreoffice/releases/tag/v4.0.0) of this package that works with the latest LibreOffice 7.3!

[Check out the docs for a new package here.](https://github.com/shelfio/aws-lambda-libreoffice#usage-for-version-4x-based-on-a-lambda-docker-image)

We're not going to support the previous version of a package that worked with a Lambda Layer and an old 6.4 version of LibreOffice.

Feel free to open new issues in regards to the new version.
