### ISSUE TITLE
Cannot read property "1" of null

### ISSUE THREAD

**Issue by BradleyDHobbs** [shelfio/aws-lambda-libreoffice#130]
I'm running this package inside of lambda to process many documents simultaneously. It's working great.

However, I'm getting this issue when lambda runs one of my documents. 

Here's the error:
`{
  "name": "DocumentConversionFailed",
  "input": {
    "Error": "TypeError",
    "Cause": "{\"errorType\":\"TypeError\",\"errorMessage\":\"Cannot read property '1' of null\",\"trace\":[\"TypeError: Cannot read property '1' of null\",\"    at getConvertedFilePath (/var/task/node_modules/@shelf/aws-lambda-libreoffice/lib/logs.js:9:54)\",\"    at convertTo (/var/task/node_modules/@shelf/aws-lambda-libreoffice/lib/convert.js:44:41)\",\"    at processTicksAndRejections (internal/process/task_queues.js:93:5)\",\"    at async ConvertDocumentToPDF (/var/task/index.js:129:26)\",\"    at async Runtime.exports.handler (/var/task/index.js:92:21)\"]}"
  }
}`

You can see the line numbers in there to possibly debug.

I can send the file I'm trying to convert if needed. I have recreated this 3-4 times with the same file. Not sure if it's the file or something wrong with "warm" lambdas.

I'm debugging this and will post back here if I find any more information.

Thanks

**Comment by harshitgupta** [comment]
@BradleyDHobbs Can you please elaborate more on how you resolved it?

I am facing the same issue. In my case, I am generating the word document using an npm module called `docx-merger` (merges multiple word documents) and facing this error while converting it to PDF.

**Comment by vladgolubev** [comment]
We've [released a major version](https://github.com/shelfio/aws-lambda-libreoffice/releases/tag/v4.0.0) of this package that works with the latest LibreOffice 7.3!

[Check out the docs for a new package here.](https://github.com/shelfio/aws-lambda-libreoffice#usage-for-version-4x-based-on-a-lambda-docker-image)

We're not going to support the previous version of a package that worked with a Lambda Layer and an old 6.4 version of LibreOffice.

Feel free to open new issues in regards to the new version.
