### ISSUE TITLE
Can't convert any msg and some docx files to pdf

### ISSUE THREAD

**Issue by LLDmitry** [shelfio/aws-lambda-libreoffice#134]
Lambda nodejs10 + lambda layer libre_office with Brotli.
On attempt to convert docx document where section "Table of Contents", i get error "Please verify input parameters... (SfxBaseModel::impl_store file:///tmp/file.pdf failed: 0xc10(Error Area:Io Class:Write Code:16))"
In result of conversion *.msg files I get unreadable pdf files with mix of ???? symbols + original text

**Comment by iamrahulroy** [comment]
@LLDmitry were you able to debug the issue?

**Comment by evrardts** [comment]
Same issue here, @LLDmitry @iamrahulroy  have you found a solution for that issue? Thanks!

**Comment by iamrahulroy** [comment]
Hi, @evrardts! Honestly I don't remember, but it looks like a font issue with file.

**Comment by vladgolubev** [comment]
We've [released a major version](https://github.com/shelfio/aws-lambda-libreoffice/releases/tag/v4.0.0) of this package that works with the latest LibreOffice 7.3!

[Check out the docs for a new package here.](https://github.com/shelfio/aws-lambda-libreoffice#usage-for-version-4x-based-on-a-lambda-docker-image)

We're not going to support the previous version of a package that worked with a Lambda Layer and an old 6.4 version of LibreOffice.

Feel free to (re)-open a new issue in regards to the recent package version.
