### ISSUE TITLE
Big CSV files(100+ MB) timing out at max resources

### ISSUE THREAD

**Issue by iamrahulroy** [shelfio/aws-lambda-libreoffice#142]
I wonder how you deal with big files? 

**Lambda Settings**
- 3000 MB Ram
- Timeout is 15 minutes

The conversion process is taking all the time. There are no other heavy operations. Other operations account for less than 500ms. 

One solution is to split the files into manageable pieces, process it independently, and join it together once processing is complete. Is that a good solution?

@vladgolubev I'm curious how you guys are dealing with the problem?

_PS: This is not an issue with the library, but a general question. Feel free to close it._

**Comment by vladgolubev** [comment]
Did you try giving Lambda 10 GB of RAM? Should help now.
