### ISSUE TITLE
LibreOffice can support image conversion

### ISSUE THREAD

**Issue by BradleyDHobbs** [shelfio/aws-lambda-libreoffice#143]
Any reason why canBeConvertedToPDF return false for images even though LibreOffice can convert the most popular image types to pdf?

For example, PNGs can be converted to pdf fine with LibreOffice.

**Comment by jpike88** [comment]
yeah, im getting a 'file is not convertible to pdf' and that's a real pain.

**Comment by vladgolubev** [comment]
The fix is simple. This helper function is exported for your convenience. You are not obliged to use it. Just invoke the `convertTo()` method directly without `canBeConvertedToPDF()`
