### ISSUE TITLE
Convert html to pdf

### ISSUE THREAD

**Issue by LLDmitry** [shelfio/aws-lambda-libreoffice#148]
Hello
A couple mistakes on converting html->pdf:
I need convert  msg files to pdf. As LibreOffice can't convert msg to pdf directly, i do pre-conversion msg-> html by another converter app. And AWS Lambda with LibreOffice converts this html to pdf.
Result pdf contains empty, extra first blank page and doesn't contain "From" email part. I've tried desktop LibreOffice app, it converts the same html correctly.

**Comment by vladgolubev** [comment]
We've [released a major version](https://github.com/shelfio/aws-lambda-libreoffice/releases/tag/v4.0.0) of this package that works with the latest LibreOffice 7.3!

[Check out the docs for a new package here.](https://github.com/shelfio/aws-lambda-libreoffice#usage-for-version-4x-based-on-a-lambda-docker-image)

We're not going to support the previous version of a package that worked with a Lambda Layer and an old 6.4 version of LibreOffice.

Feel free to open new issues in regards to the new version.
