### ISSUE TITLE
File not being created, failing silently

### ISSUE THREAD

**Issue by killarneyman** [shelfio/aws-lambda-libreoffice#151]
I have experienced an issue similar to this -  #39 

It's periodic, soffice.bin returns the expected `convert /tmp/whatever.docx -> /tmp/whatever.pdf using filter : writer_pdf_Export` as expected, but the file is not created.
I tried following a similar path as in issue #39 , but it appears those changes have already been implemented into the library.

The file converts as expected using a similar conversion process on the osx version of the soffice command line tool, it's only using this layer that it fails.

If a file fails in this manner, it will always fail in this manner, most files convert fine.

Has anyone got any idea how to debug this? Has anyone experienced anything similar?

**Comment by julianpitt** [comment]
I'm getting the same error, expect my output is  `using filter : impress_pdf_Export`.
Tried debugging but not having much luck

**Comment by vladgolubev** [comment]
We've [released a major version](https://github.com/shelfio/aws-lambda-libreoffice/releases/tag/v4.0.0) of this package that works with the latest LibreOffice 7.3!

[Check out the docs for a new package here.](https://github.com/shelfio/aws-lambda-libreoffice#usage-for-version-4x-based-on-a-lambda-docker-image)

We're not going to support the previous version of a package that worked with a Lambda Layer and an old 6.4 version of LibreOffice.

Feel free to (re)-open a new issue in regards to the recent package version.
