### ISSUE TITLE
local testing

### ISSUE THREAD

**Issue by ShaMan123** [shelfio/aws-lambda-libreoffice#152]
I am rather clueless regarding the functionality of this repo but I would suggest replacing all static `tmp` with `os.tmpdir()` to enable local testing as well.
OK, rephrasing, I'd love documentation regarding local testing on non `linux` machines.

**Comment by vladgolubev** [comment]
The testing script was adapted to run in Docker now, so should be fine on all machines!

We've [released a major version](https://github.com/shelfio/aws-lambda-libreoffice/releases/tag/v4.0.0) of this package that works with the latest LibreOffice 7.3!

[Check out the docs for a new package here.](https://github.com/shelfio/aws-lambda-libreoffice#usage-for-version-4x-based-on-a-lambda-docker-image)

We're not going to support the previous version of a package that worked with a Lambda Layer and an old 6.4 version of LibreOffice.

Feel free to (re)-open a new issue in regards to the recent package version.
