### ISSUE TITLE
Failed to convert if instance of lambda if re-used

### ISSUE THREAD

**Issue by Dizmus** [shelfio/aws-lambda-libreoffice#155]
Hello,

Please try the Lambda Function source code attached. 

Issue is reproduced when running two requests, one after another. In this case, instance of Lambda Function is reused and all next calls will be failed.

If you wait couple of minutes for Lambda instance to shutdown, it will run normal

[LibreOfficeNPM.zip](https://github.com/shelfio/aws-lambda-libreoffice/files/5712446/LibreOfficeNPM.zip)

**Comment by evrardts** [comment]
Hey @Dizmus have you found a solution to your issue? I am facing the same problem here.

**Comment by Dizmus** [comment]
Hi @evrardts , 
No, I am finished with hosting a custom service on Fargate.

Just used an Alpine Docker image and installed libreoffice with all it's dependencies. 

P.S. Docker in Lambda with Libreoffice also doesn't work, since Lambda doesn't really runs docker image. It just grabs the dependencies. While it works locally on Docker daemon, it doesn't on Lambda

**Comment by maurice-ellis** [comment]
Just incase anyone runs into this issue later. The error I kept getting if reused was that the default font config file was not found. I followed these steps to create a `fonts.conf` file for my function after now 6 tries, it runs smooth as butter. Even checked to see if it was already unpacked before unpacking again.

[https://stackoverflow.com/a/51622335](Create fonts.conf)

**Comment by anjanvb** [comment]
I can confirm that @maurice-ellis' method works. It makes the bundle size large though so I am going to try making the fonts in it's own layer.

**Comment by cesarpachon** [comment]
hello, I am getting blank documents after the first successful attempt; even after  I got rid of the font config file error message. 
In my case I am opening a odt file and saving to pdf. the first time it renders OK, the second time it renders blank with no error messages.

**Comment by vladgolubev** [comment]
We've [released a major version](https://github.com/shelfio/aws-lambda-libreoffice/releases/tag/v4.0.0) of this package that works with the latest LibreOffice 7.3!

[Check out the docs for a new package here.](https://github.com/shelfio/aws-lambda-libreoffice#usage-for-version-4x-based-on-a-lambda-docker-image)

We're not going to support the previous version of a package that worked with a Lambda Layer and an old 6.4 version of LibreOffice.

Feel free to (re)-open a new issue in regards to the recent package version.
