### ISSUE TITLE
Suggestion: increase memory recommendation

### ISSUE THREAD

**Issue by matthias-schoeneich** [shelfio/aws-lambda-libreoffice#166]
Hi,

using your project and it works very nice 

However when documents reach a certain complexity, libreoffice fails to start and therefor is unable to render.  We use carbone.js to replace parameters in template files and create pdfs. We used the minimum recommended memory setting 1536mb. 

On the other hand [aws docs](https://docs.aws.amazon.com/lambda/latest/dg/configuration-function-common.html) state that at 1769mb one full core is allocated. That means, until that some kind of throttling applies. As lambdas scale linear with memory, that 1536mb should give about 86.8% of an vcpu.

When running lo locally using lambci/lambda:nodejs12.x no problem occurred so far. To test the theory, param `--cpus="0.868"` was added to docker run. Guess what? Lo failed to start as it does when deployed as lambda. My knowledge of the inner workings of Lo is not existing, but for me it looks like one of the lo components does not like to be interrupted. Once that was at least reproduceable, an increase of lambda memory to 1769mb(1 vcpu) solved the problem. 

stacktrace we got until that change looks like this:
```                                                             
Fatal exception: Signal 6                                     
Stack:                                                        
/tmp/instdir/program/libuno_sal.so.3(+0x13deb)[0x7f56a386fdeb]
/tmp/instdir/program/libuno_sal.so.3(+0x3ad13)[0x7f56a3896d13]
/lib64/libpthread.so.0(+0x117e0)[0x7f56a2d777e0]              
/lib64/libc.so.6(gsignal+0x110)[0x7f56a29eeb20]               
/lib64/libc.so.6(abort+0x148)[0x7f56a29effc8]                 
```

Thank you for your work
Matthias

**Comment by vladgolubev** [comment]
Added here: https://github.com/shelfio/aws-lambda-libreoffice#lambda-configuration

Thanks!
