### ISSUE TITLE
Publish as a Lambda Layer

### ISSUE THREAD

**Issue by vladgolubev** [shelfio/aws-lambda-libreoffice#38]
Due to such a huge size this dependency is heavy to install locally. Also it takes time to bundle and deploy. Ideal fit for Lambda Layers!

**Comment by andywgarcia** [comment]
@vladgolubev Quick and dirty because I thought the same thing. Here you go! https://github.com/wisedoc-inc/libre-office-lambda-layer

**Comment by vladgolubev** [comment]
Done https://github.com/shelfio/libreoffice-lambda-layer
Version 2.0.0 works only with that layer now
