### ISSUE TITLE
Error while loading shared libraries

### ISSUE THREAD

**Issue by spyridonas** [shelfio/aws-lambda-libreoffice#41]
Lambda says 

> /tmp/instdir/program/soffice.bin: error while loading shared libraries: libmergedlo.so: cannot open shared object file: No such file or directory

**Comment by sebastienfi** [comment]
@spyridonas can you please tell me what was your problem here and how you solved it?

**Comment by spyridonas** [comment]
> @spyridonas can you please tell me what was your problem here and how you solved it?

I tried other versions of libreoffice from https://github.com/vladgolubev/serverless-libreoffice/releases/ and I think I ended up with 5.4.3

**Comment by sebastienfi** [comment]
Thanks!
