### ISSUE TITLE
Is there a way to run this locally?

### ISSUE THREAD

**Issue by Shion093** [shelfio/aws-lambda-libreoffice#65]
I'm using serverless-offline on MacOS, when I try to run the converter locally it says

```javascript 
no suitable image found.  Did find:
     node_modules/@shelf/aws-lambda-brotli-unpacker/src/iltorb/build/bindings/iltorb.node: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
       node_modules/@shelf/aws-lambda-brotli-unpacker/src/iltorb/build/bindings/iltorb.node: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
```

Is this meant only for running on a deployed environment or there is another way to make ti work locally?

Thanks

**Comment by vladgolubev** [comment]
Hey @Shion093 

Right now local support is not even planned to be supported. That would imply a huge amount of work to compile LibreOffice for each OS, or expect user to have a specific LibreOffice installed...

**Comment by Shion093** [comment]
Thanks for the reply. 

I ended up running an Ubuntu VM and it works!! 

Thanks for this awesome package, really appreciate it.

**Comment by jessrosenfield** [comment]
> Hey @Shion093
> 
> Right now local support is not even planned to be supported. That would imply a huge amount of work to compile LibreOffice for each OS, or expect user to have a specific LibreOffice installed...

I disagree that local support requires bundling and unpacking the program for each OS. Ideally I'd be able to run the API locally by providing my own path to LibreOffice and skipping the unpacking step.

**Comment by jessrosenfield** [comment]
Alternatively, is there a local complement with the same API that I can run locally? (Akin to using `puppeteer` locally vs `chrome-aws-lambda` remotely?)
